language: r

cache:
  directories:
    - _book
  packages: true
  
apt_packages:
  - libxml2-dev

before_install:
  - nvm install stable
  - npm install netlify-cli -g

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: script
  script: netlify deploy --prod --dir _book
  skip_cleanup: true
